nelmio_api_doc:
    documentation:
        info:
            title: Thesis
            description: This is backend app is for storing blocks, sequences, and modifications.
            version: 1.0.0
        components:
            securitySchemes:
                ApiKeyAuth:
                    type: apiKey
                    description: 'Token authentification'
                    name: x-auth-token
                    in: header
        security:
            - ApiKeyAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/rest
